apiVersion: apps/v1
kind: Deployment
metadata:
  name: egroup-bot
  namespace: egroup-bot
  labels:
    app: egroup-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egroup-bot
  template:
    metadata:
      labels:
        app: egroup-bot
    spec:
      containers:
      - name: egroup-bot
        image: ghcr.io/bpafoshizle/egroup-bot:latest
        env:
        - name: LOGLEVEL
          value: "INFO"
        - name: POLYGON_TOKEN
          valueFrom:
            secretKeyRef:
              name: stock
              key: polygon-token
        - name: NEWSAPI_TOKEN
          valueFrom:
            secretKeyRef:
              name: stock
              key: newsapi-token
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord
              key: token
        - name: DSCRD_CHNL_BOT_TESTING
          valueFrom:
            secretKeyRef:
              name: discord
              key: dscrd-chnl-bot-testing
        - name: DSCRD_CHNL_GENERAL
          valueFrom:
            secretKeyRef:
              name: discord
              key: dscrd-chnl-general
        - name: DSCRD_CHNL_MEAL_PICS
          valueFrom:
            secretKeyRef:
              name: discord
              key: dscrd-chnl-meal-pics
        - name: DSCRD_CHNL_SPORTS
          valueFrom:
            secretKeyRef:
              name: discord
              key: dscrd-chnl-sports
        - name: DSCRD_CHNL_POLITICS
          valueFrom:
            secretKeyRef:
              name: discord
              key: dscrd-chnl-politics
        - name: DSCRD_CHNL_MONEY
          valueFrom:
            secretKeyRef:
              name: discord
              key: dscrd-chnl-money
        - name: DSCRD_CHNL_GAMING
          valueFrom:
            secretKeyRef:
              name: discord
              key: dscrd-chnl-gaming
        - name: DSCRD_CHNL_BOT_FEATURE_REQUESTS
          valueFrom:
            secretKeyRef:
              name: discord
              key: dscrd-chnl-bot-feature-requests
        - name: TWITCH_BOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: twitch
              key: twitch-bot-username
        - name: TWITCH_BOT_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: twitch
              key: twitch-bot-client-id
        - name: TWITCH_BOT_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: twitch
              key: twitch-bot-client-secret
        - name: TWITCH_CHAT_OAUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: twitch
              key: twitch-chat-oauth-token
      imagePullSecrets:
      - name: ghcr-egroup-bot
