apiVersion: apps/v1
kind: Deployment
metadata:
  name: egroup-bot
  namespace: egroup-bot
  labels:
    app: egroup-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egroup-bot
  template:
    metadata:
      labels:
        app: egroup-bot
    spec:
      containers:
      - name: egroup-bot
        image: ghcr.io/bpafoshizle/egroup-bot:latest
        env:
        - name: LOGLEVEL
          value: "INFO"
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord
              key: token
        - name: DSCRD_PROD_CHNL_BOT_TESTING
          valueFrom:
            secretKeyRef:
              name: discord
              key: dscrd-chnl-bot-testing
        - name: DSCRD_PROD_CHNL_GENERAL
          valueFrom:
            secretKeyRef:
              name: discord
              key: dscrd-chnl-general
        - name: DSCRD_PROD_CHNL_MEAL_PICS
          valueFrom:
            secretKeyRef:
              name: discord
              key: dscrd-chnl-meal-pics
        - name: DSCRD_PROD_CHNL_SPORTS
          valueFrom:
            secretKeyRef:
              name: discord
              key: dscrd-chnl-sports
        - name: DSCRD_PROD_CHNL_POLITICS
          valueFrom:
            secretKeyRef:
              name: discord
              key: dscrd-chnl-politics
        - name: DSCRD_PROD_CHNL_MONEY
          valueFrom:
            secretKeyRef:
              name: discord
              key: dscrd-chnl-money
        - name: DSCRD_PROD_CHNL_GAMING
          valueFrom:
            secretKeyRef:
              name: discord
              key: dscrd-chnl-gaming
        - name: DSCRD_PROD_CHNL_BOT_FEATURE_REQUESTS
          valueFrom:
            secretKeyRef:
              name: discord
              key: dscrd-chnl-bot-feature-requests


      imagePullSecrets:
      - name: ghcr-egroup-bot
